stages:
  - initialize
  - test
  - deploy

default:
  image: node:16
  before_script:
    - corepack enable

initialize:
  stage: initialize
  cache:
    key:
      files:
        - pnpm-lock.yaml
    policy: pull-push
    paths:
      - node_modules
    untracked: true
  script:
    - pnpm install
    - pnpm vercel pull --yes --environment=preview --token=${VERCEL_TOKEN}
    - pnpm vercel env pull --yes --environment=preview --token=${VERCEL_TOKEN} .env.local
    - pnpm codegen
  artifacts:
    paths:
      - 'node_modules'
      - '**/generated/**'
    untracked: true
    expire_in: '1 week'

test:
  stage: test
  needs:
    - initialize
  script:
    - pnpm lint
    - pnpm test

deploy_preview:
  stage: deploy
  except:
    - main
  needs:
    - initialize
    - test
  script:
    - pnpm vercel pull --yes --environment=preview --token=${VERCEL_TOKEN}
    - pnpm vercel build --token=$VERCEL_TOKEN
    - pnpm vercel deploy --prebuilt  --token=$VERCEL_TOKEN

deploy_production:
  stage: deploy
  only:
    - main
  needs:
    - initialize
    - test
  script:
    - pnpm vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - pnpm vercel build --prod --token=$VERCEL_TOKEN
    - pnpm vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
