import {
  Flex,
  FormControl,
  FormLabel,
  Input,
  Button,
  Center,
  Box,
  Skeleton,
  Stack
} from '@chakra-ui/react';
import Head from 'next/head';
import { useForm } from 'react-hook-form';

interface SubmitByUrlForm {
  password: string;
}

const Activation = () => {
  // ! TEMP
  const loading = false;
  const error = false;
  // !============

  const {
    register,
    handleSubmit,
    formState: { errors }
  } = useForm<SubmitByUrlForm>();

  const onSubmit = handleSubmit((data) => {
    const password = data.password;
    console.log('password', password);
    console.log('url', document.URL);
  });

  return (
    <>
      <Head>
        <title>Activation</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.svg' />
      </Head>
      <Center>
        <Box w='lg' py={8}>
          {error ? <>Error</> : <></>}
          <Skeleton isLoaded={!loading}>
            <Stack>
              <form onSubmit={onSubmit}>
                <Flex direction='column' gap={4}>
                  <FormControl>
                    <FormLabel>Password</FormLabel>
                    <Input
                      {...register('password', { required: true })}
                      type='password'
                    />
                    {errors.password && <span>This field is required.</span>}
                  </FormControl>
                  <Button type='submit' colorScheme='brand-primary'>
                    Activate
                  </Button>
                </Flex>
              </form>
            </Stack>
          </Skeleton>
        </Box>
      </Center>
    </>
  );
};

export default Activation;
